### PR TITLE
Only play music from configured music folder

### PR DESCRIPTION
**Pull request by BafDyce**

### CODE REVIEW

**Comment by Lartza** [comment]
I don't see what this accomplishes since the current code doesn't play music outside the folder either?

**Comment by BafDyce** [comment]
It does if you do prepend one or more '../' to the file you want to play.

**Comment by azlux** [comment]
hi,
`/` isn't authorized !
See https://github.com/azlux/MumbleRadioPlayer/commit/4fb9bc2098b23f01470f1668b35a9a9b5b99cfc2

**Comment by BafDyce** [comment]
Oh. So thats the reason why '/' are not allowed?
Then, using the following code:

    music_folder = self.config.get('bot', 'music_folder')
    path = os.path.abspath(os.path.join(music_folder, parameter))
    if path.startswith(music_folder) and os.path.isfile(path):
        self.launch_play_file(path)


Would allow subfolders while also preventing this issue.

**Comment by azlux** [comment]
@BafDyce That's actually not the goal of this bot.
I'm actually working on https://github.com/azlux/botamusique projet. Subfolder, URL, Radio.... Everything into one bot. (It's work in progress, I haven't commit my last implementations)

**Comment by BafDyce** [comment]
Ah, I see. Thanks for the info!

**Comment by BafDyce** [comment]
When will you push your latest updates to botamusique? ;)

For now, I think you can close this PR.

**Comment by azlux** [comment]
in few days, I need to finish working and installing my new server, and I will finish to code the bot to make the basic work.

**Pull request closed without merging**
